[tool.poetry]
name = "your-project-name"
version = "0.1.0"
description = ""
authors = ["Arnav Patil <arnavpatil455@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
